version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OBSIDIAN_VAULT_PATH=/app/vault
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - CHROMA_URL=http://chroma:8000
    volumes:
      - ./path/to/your/vault:/app/vault
    depends_on:
      - ollama
      - chroma
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped

volumes:
  ollama_data:
  chroma_data:
